export type Speaker = {
  id: string;
  name: string;
  credentials?: string;
  title: string;
  organization: string;
  bio: string;
  photo: string;
  photoPosition?: string;
};

export type Session = {
  time: string;
  title: string;
  speakerIds?: string[];
  type?: "break" | "session";
};

export type DaySchedule = {
  day: string;
  date: string;
  sessions: Session[];
};

export const speakers: Record<string, Speaker> = {
  "dave-schoolcraft": {
    id: "dave-schoolcraft",
    name: "Dave Schoolcraft",
    credentials: "JD",
    title: "Partner and Chair, Digital Health Team",
    organization: "Ogden Murphy Wallace",
    bio: "Dave Schoolcraft has worked for more than 25 years at the intersection of health care, law and all things digital. He is a Partner and Chair of the Digital Health Team at the Ogden Murphy Wallace law firm in Seattle. He provides strategic guidance to health care provider organizations and technology companies seeking to drive health system transformation. Dave has a national practice advising clients on technology licensing, artificial intelligence, data governance, health information privacy and security issues. Dave is also the founder of the Digital Health Group, LLC which produces collaborative events for those working on the next wave of AI and data-driven innovation in health care.",
    photo: "/images/speakers/dhc-2024/dave-schoolcraft.jpg",
  },
  "martin-stumpe": {
    id: "martin-stumpe",
    name: "Martin Stumpe",
    credentials: "PhD",
    title: "Chief Data & Artificial Intelligence Officer",
    organization: "Danaher",
    bio: "Dr. Martin Stumpe is the Chief Data & Artificial Intelligence Officer at Danaher, where he leads the company's AI strategy, capability development, and execution. Prior to this role, he was the Chief of AI at Tempus, a precision medicine company, where he built and led the AI and Data Science department. At Tempus, his teams applied machine learning to facilitate genomic testing, real world evidence data generation, clinical trial enrollment, and AI-powered diagnosis and decision support in oncology and cardiology. Dr. Stumpe holds a PhD in Computational and Theoretical Physics from the Max Planck Institute for Biophysical Chemistry in Germany.",
    photo: "/images/speakers/dhc-2024/martin-stumpe.jpg",
  },
  "tayab-waseem": {
    id: "tayab-waseem",
    name: "Tayab Waseem",
    credentials: "MD, PhD",
    title: "Emergency Medicine Physician",
    organization: "Virginia Commonwealth University",
    bio: "Dr. Tayab Waseem holds two bachelor's degrees in Biology and Bioinformatics from Virginia Commonwealth University. He completed his MD and received his Ph.D. in Immunology from Eastern Virginia Medical School. He has done fellowships in public policy and venture capital. During his medical training Dr. Waseem chaired the White House Office of Science and Technology Policies flagship project using technology to combat the COVID-19 pandemic with the creation of an AI powered live literature review. His work on this project led him to co-found and serve as Chief Scientific Officer of Stability AI, the world's largest Open Source Generative AI company.",
    photo: "/images/speakers/dhc-2024/tayab-waseem.jpg",
  },
  "sebastian-jayaraj": {
    id: "sebastian-jayaraj",
    name: "Sebastian Jayaraj",
    credentials: "PhD",
    title: "Health Tech Innovation Leader",
    organization: "",
    bio: "Sebastian Jayaraj's expertise is in health tech innovation, strategy and commercialization. He has led programs for artificial intelligence safety and regulation, and investor engagement at the FDA. As part of The White House Artificial Intelligence Executive Order Task Force, he helped implement responsible AI strategies across federal health agencies under HHS. Prior to the FDA, he was Executive Director of Product at Providence Health. His digital products are widely used by patients and researchers and have garnered media coverage as pioneering approaches. He holds patents and peer-reviewed publications in health tech, genomics, and management. Dr. Jayaraj received his PhD Strategy from Rutgers University, MS Computer Science from the University of Pennsylvania, and BS Biology from Bangalore University.",
    photo: "/images/speakers/dhc-2024/sebastian-jayaraj.jpg",
  },
  "jefferson-lin": {
    id: "jefferson-lin",
    name: "Jefferson Lin",
    credentials: "JD",
    title: "Attorney",
    organization: "Fenwick",
    bio: "Jefferson Lin represents digital health, life sciences and technology companies in complex transactions. He regularly counsels clients with respect to intellectual property licensing, data privacy and security, and healthcare regulatory issues. He is also involved in corporate transactions such as mergers, asset acquisitions and venture capital investments. Jefferson received his JD from the University of Washington School of Law and his BA from Williams College.",
    photo: "/images/speakers/dhc-2024/jefferson-lin.jpg",
  },
  "maggie-huston": {
    id: "maggie-huston",
    name: "Maggie Huston",
    credentials: "JD",
    title: "Deputy General Counsel",
    organization: "Tempus AI",
    bio: "Maggie Huston is Deputy General Counsel at Tempus AI, a technology company and clinical laboratory advancing precision medicine through the practical application of artificial intelligence in healthcare. At Tempus, Maggie supports clinical laboratory operations, in vitro diagnostic and artificial intelligence/machine learning product development, and real world data initiatives. She also negotiates a range of clinical and research collaborations with healthcare providers, academic research institutions, and life sciences companies. Prior to Tempus, Maggie was a member of the legal team at Epic, which develops electronic health record software for health systems. Maggie earned her JD from Harvard Law School and a BA from Boston University.",
    photo: "/images/speakers/dhc-2024/maggie-huston.jpg",
  },
  "brandon-fornwalt": {
    id: "brandon-fornwalt",
    name: "Brandon Fornwalt",
    credentials: "MD, PhD",
    title: "Senior Vice President of Cardiology",
    organization: "Tempus",
    bio: "Dr. Brandon Fornwalt graduated from the University of South Carolina Honors College in 2002 with an undergraduate degree in mathematics and marine science. He then worked in a free medical clinic for a year before starting an MD/PhD program at Emory and Georgia Tech. After finishing his degrees in 2010, he completed an internship in pediatrics at Boston Children's Hospital before becoming an Assistant Professor at the University of Kentucky. After four years on faculty in Kentucky, Dr. Fornwalt moved with his research team to Geisinger where he completed his diagnostic radiology residency and founded Geisinger's Department of Translational Data Science and Informatics. In 2021, Dr. Fornwalt took a position at Tempus as the Senior Vice President of Cardiology where he leads the scientific and clinical aspects of Tempus' data-driven cardiology efforts. Dr. Fornwalt is also a part-time radiologist at UPMC Williamsport.",
    photo: "/images/speakers/dhc-2024/mark-knee.jpg",
    photoPosition: "right center",
  },
  "michael-lipinski": {
    id: "michael-lipinski",
    name: "Michael Lipinski",
    title: "Director, Regulatory and Policy Affairs Division",
    organization: "ASTP (formerly ONC)",
    bio: "Michael Lipinski is the Director of the Regulatory and Policy Affairs Division within the Office of the Assistant Secretary for Technology Policy (ASTP). Michael leads ASTP's development of regulations and contributes to HHS policies, regulations, and initiatives that support the adoption and use of health IT, secure electronic health information access and exchange, and patient privacy. Before coming to ASTP, Michael served as the Senior Legal Advisor to the head of the HHS Office of Medicare Hearings and Appeals. Michael received his law degree from Georgetown University Law Center.",
    photo: "/images/speakers/dhc-2024/michael-lipinski.jpg",
  },
  "mark-knee": {
    id: "mark-knee",
    name: "Mark Knee",
    credentials: "JD",
    title: "Director, Interoperability Division",
    organization: "ASTP (formerly ONC)",
    bio: "Mark Knee is the Director of the Interoperability Division within the U.S. Department of Health and Human Service's Assistant Secretary for Technology Policy (ASTP), where he works on health IT and interoperability law and policy. Prior to coming to ASTP, Mark worked in different capacities within the federal government assisting federal agencies in policymaking and enforcement activities. Mark earned his J.D. from William & Mary Law School and was a Presidential Management Fellow.",
    photo: "/images/speakers/dhc-2024/brandon-fornwalt.jpg",
    photoPosition: "center 30%",
  },
  "matthew-holt": {
    id: "matthew-holt",
    name: "Matthew Holt",
    credentials: "PhD",
    title: "Founder, The Health Care Blog",
    organization: "THCB / SMACK.health",
    bio: "Matthew Holt: I'm an old curmudgeon in the world of health technology. Best known as the founder of The Health Care Blog (THCB) and (with Indu Subaiya) the Health 2.0 conferences, I now split my time between THCB, and the SMACK.health Advisory service for health tech startups. During my career I've spent nearly 30 years in health care and health care IT as a generalist forecaster and strategist, I've worked for renowned forecasting (IFTF) and polling (Harris) organizations, conducted several ground breaking in-depth studies about many aspects of health care, and delivered several keynote addresses all over the world (and now all over Zoom). I know a few people too.",
    photo: "/images/speakers/dhc-2024/matthew-holt.jpg",
  },
  "brendan-keeler": {
    id: "brendan-keeler",
    name: "Brendan Keeler",
    title: "Interoperability Practice Lead",
    organization: "HTD Health",
    bio: "Brendan Keeler is the Interoperability Practice Lead at HTD Health, a digital health consultancy and development agency, and author of the Health API Guy newsletter. Prior to joining HTD, Brendan served as Head of Product at Flexpa, and held product roles at Zus Health, Redox and Epic. He brings industry-defining perspective and unparalleled expertise in health data formats, standards, and data engineering best practices.",
    photo: "/images/speakers/dhc-2024/brendan-keeler.jpg",
  },
  "kat-duncan": {
    id: "kat-duncan",
    name: "Kat Duncan",
    title: "Attorney",
    organization: "",
    bio: "Kat Duncan advises emerging and high-growth companies on a wide variety of issues, including corporate governance, financings, equity and employment issues and licensing and commercial matters. She also represents late-stage private and public companies, as well as underwriters in public offerings, and counsels public companies on corporate governance, securities and compliance issues. Kat has been selected in Super Lawyers as a \"Rising Star\" for nine consecutive years (2013 – 2022).",
    photo: "/images/speakers/dhc-2024/kat-duncan.jpg",
  },
  "oren-nissim": {
    id: "oren-nissim",
    name: "Oren Nissim",
    title: "CEO and Co-Founder",
    organization: "Brook",
    bio: "When Oren was diagnosed with type 2 diabetes in 2002, he wasn't sure what to do. At first, he tried to ignore it. But after learning more about the health complications caused by uncontrolled blood sugar, he decided it was time to take control of his health for his wife and three children. That's when he discovered a gap in the market — he got support at his doctor appointments, but what about the day-to-day management after he left the office? That's when he came up with the idea for Brook. Oren built a team and started creating products that integrate the best of the technology and healthcare worlds. Brook brings people at all stages of health tools they can use anytime, and anywhere they need it.",
    photo: "/images/speakers/dhc-2024/oren-nissim.jpg",
  },
  "casey-moriarty": {
    id: "casey-moriarty",
    name: "Casey Moriarty",
    credentials: "JD",
    title: "Attorney, Health Care Practice Group",
    organization: "Ogden Murphy Wallace",
    bio: "Casey Moriarty is an attorney in the Ogden Murphy Wallace health care practice group. Casey represents hospitals, community health centers, provider networks, and other health care providers with transactional and compliance issues. Casey works extensively on legal issues related to patient privacy, including compliance with HIPAA, and the HITECH Act. Casey also advises health care entities on governance, compliance, and transactional issues related to the formation of clinically integrated networks, accountable care organizations, and other health reform initiatives that are focused on value-based care. Casey received his bachelor's degree from Yale University and his law degree from Seattle University.",
    photo: "/images/speakers/dhc-2024/casey-moriarty.jpg",
    photoPosition: "right center",
  },
  "jenny-cronin": {
    id: "jenny-cronin",
    name: "Jenny Cronin",
    credentials: "PhD",
    title: "Principal",
    organization: "AI2 Incubator",
    bio: "Jenny Cronin is a Principal at AI2 Incubator, a pre-seed startup incubator and investor, where she focuses on startups at the intersection of AI + healthcare and biotech. Prior to joining AI2 Incubator, Jenny was a product manager at NanoString leading their GeoMx Digital Spatial Profiler antibody portfolio, and a science communications advisor at a boutique PR firm working with early-stage biotech clients. Jenny received her PhD in Bioengineering from UW with research on brain-computer interfaces for touch restoration.",
    photo: "/images/speakers/dhc-2024/jenny-cronin.jpg",
  },
  "adriana-lein": {
    id: "adriana-lein",
    name: "Adriana Lein",
    credentials: "JD, MSc",
    title: "Associate, Healthcare Group",
    organization: "Ogden Murphy Wallace",
    bio: "Adriana Lein is an associate in the Healthcare group of Ogden Murphy Wallace's Seattle Office. In this role, she advises healthcare providers and technology companies on matters related to digital health, health information privacy and security, employment laws, and a range of corporate transactions and regulatory issues. Prior to legal practice, Adriana's professional experiences focused on global health equity and public policy while affiliated with Duke University and the Urban Health Collaborative. She received her JD from the University of Washington where she served as the Executive Articles Editor of the Washington Law Review.",
    photo: "/images/speakers/dhc-2024/adriana-lein.jpg",
  },
  "doreen-fadaeiforghan": {
    id: "doreen-fadaeiforghan",
    name: "Doreen Fadaeiforghan",
    credentials: "JD",
    title: "Associate, Healthcare and Litigation Group",
    organization: "Ogden Murphy Wallace",
    bio: "Doreen Fadaeiforghan is an associate in the Healthcare and Litigation group at Ogden Murphy Wallace. In this role, she advises healthcare entities on government investigations, the development of AI for healthcare entities and healthcare litigation. Originally from Iran, she has a background in computer science and is passionate about the intersection of AI and healthcare. Doreen holds a JD from Seattle University, where she was an editor of the Seattle Journal of Technology, Environmental, & Innovation Law, and a BA in Fashion Merchandising.",
    photo: "/images/speakers/dhc-2024/alieza-ali.jpg",
  },
  "katherine-robertson": {
    id: "katherine-robertson",
    name: "Katherine Robertson",
    credentials: "JD",
    title: "Associate, Health Care Group",
    organization: "Ogden Murphy Wallace",
    bio: "Katherine Robertson is an associate in the health care group at the Ogden Murphy Wallace law firm in Seattle. Her practice includes advising clients on issues of regulatory compliance, data governance, and complex technology contracts. Prior to law school, Katherine worked in patient care, which has informed her ongoing passion regarding health information privacy and security, artificial intelligence, and interoperability.",
    photo: "/images/speakers/dhc-2024/katherine-robertson.jpg",
  },
  "ty-kayam": {
    id: "ty-kayam",
    name: "Ty Kayam",
    title: "Principal Corporate Counsel, Health & Life Sciences",
    organization: "Microsoft",
    bio: "Ty Kayam is Principal Corporate Counsel for Health & Life Sciences at Microsoft, where she leads its health regulatory and policy efforts and serves as product counsel for Microsoft's health AI product suite. In this role, she advises product, engineering, and data science teams on legal issues related to the development of AI and other emerging technologies for the health industry. She also helps shape Microsoft's policy priorities and positions on health AI and digital health globally. Before joining Microsoft, Ty was counsel at a large health information network, handling health regulatory matters and technology transactions. She began her career in the healthcare practice group of Feldesman Tucker Leifer Fidell. Ty holds a Master's in Public Health from Tufts University and a law degree from Northeastern University School of Law.",
    photo: "/images/speakers/dhc-2024/doreen-fadaeiforghan.jpg",
  },
  "alieza-ali": {
    id: "alieza-ali",
    name: "Alieza Ali",
    title: "Senior Corporate Counsel, Privacy, Safety, and Regulatory Affairs",
    organization: "Microsoft",
    bio: "Alieza Ali is a Senior Corporate Counsel in the Privacy, Safety, and Regulatory Affairs legal group at Microsoft, where she advises attorneys that support engineers on complex privacy issues in product development and engages with regulators on a deeper understanding of Microsoft's posture in privacy. Previously, she has worked at several technology and healthcare companies, counseling her clients in transactional, intellectual property, and regulatory issues in telehealth and digital health.",
    photo: "/images/speakers/dhc-2024/ty-kayam.jpg",
  },
  "harsha-nori": {
    id: "harsha-nori",
    name: "Harsha Nori",
    title: "Director of Research Engineering, Aether",
    organization: "Microsoft",
    bio: "Harsha Nori is the Director of Research Engineering for Aether, Microsoft's internal group focused on AI, Engineering, and ethics. He leads an interdisciplinary team dedicated to developing more responsible AI systems and bringing responsible AI research to practitioners through open-source tools, libraries, and integrations into ML platforms. Nori co-founded the InterpretML framework, which is widely used by data scientists and ML engineers for building interpretable models and explaining opaque model predictions.",
    photo: "/images/speakers/dhc-2024/glenn-cohen.jpg",
  },
  "glenn-cohen": {
    id: "glenn-cohen",
    name: "Glenn Cohen",
    title: "Professor of Law",
    organization: "Harvard Law School",
    bio: "Prof. Glenn Cohen is one of the world's leading experts on the intersection of bioethics (sometimes also called \"medical ethics\") and the law, as well as health law. He also teaches civil procedure. He has advised the U.S. Vice President on reproductive rights, discussed medical AI policy with members of the Korean Congress, and lectured to legal, medical, and industry conferences around the world. His work has been frequently covered by or appeared in PBS, NPR, ABC, NBC, CBS, CNN, MSNBC, Mother Jones, the New York Times, The Washington Post, the Boston Globe, and many other media venues. He was the youngest professor on the faculty at Harvard Law School (tenured or untenured) both when he joined the faculty in 2008 (at age 29) and when he was tenured as a full professor in 2013 (at age 34), though not the youngest in history.",
    photo: "/images/speakers/dhc-2024/harsha-nori.jpg",
  },
  "elana-zana": {
    id: "elana-zana",
    name: "Elana Zana",
    credentials: "JD",
    title: "General Counsel / Vice President, Assistant General Counsel",
    organization: "Navigating Cancer / OneOncology",
    bio: "Elana Zana is General Counsel of Navigating Cancer and Vice President/Assistant General Counsel of OneOncology. She is a former partner at Ogden Murphy Wallace. Elana provides advice on data privacy and security, certification and regulatory requirements, life sciences and pharmaceutical contracting, commercial contracts, general business matters, and what she enjoys most, strategizing with the product and engineering team on creating digital health tools to achieve better patient outcomes.",
    photo: "/images/speakers/dhc-2024/elana-zana.jpg",
  },
  "matt-soskins": {
    id: "matt-soskins",
    name: "Matt Soskins",
    title: "In-House Counsel",
    organization: "CommonSpirit Health",
    bio: "As in-house counsel at CommonSpirit Health, Matt Soskins enhances Virginia Mason Franciscan Health's innovation in healthcare operations. Matt leads CommonSpirit Health's national Sports and Entertainment Center of Excellence, negotiating and drafting agreements for medical services, sponsorships, naming rights, licensing, and media rights with entertainment companies, venues, athletes, teams, and leagues including NFL, MLB, MLS, NHL, NCAA, and PGA. In his spare time, Matt loves travel, live theater, competing in sports, teaching health law at Seattle University, and trying to be an early adopter of new ideas and technology — especially when it confuses or scares him.",
    photo: "/images/speakers/dhc-2024/zach-harned.jpg",
  },
  "zach-harned": {
    id: "zach-harned",
    name: "Zach Harned",
    title: "Associate",
    organization: "Fenwick & West",
    bio: "Zach Harned, an associate at Fenwick & West, represents digital health, life sciences, technology, and AI/ML companies in complex transactions. He specializes in intellectual property, data privacy, security, and regulatory matters, advising on venture financings, mergers, and acquisitions. Zach holds a CIPP/US certification and is a member of the International Association of Privacy Professionals. Before law, he served as a mental health professional for Veterans Affairs. During law school, he founded the Stanford Artificial Intelligence & Law Society and externed with the FDA's Center for Digital Health.",
    photo: "/images/speakers/dhc-2024/matt-soskins.jpg",
  },
  "engers-fernandez": {
    id: "engers-fernandez",
    name: "Engers Fernandez",
    credentials: "MD, MBA, MHILS",
    title: "Vice President of Innovation",
    organization: "OCHIN",
    bio: "Dr. Engers Fernandez is a visionary leader in AI and digital transformation in healthcare and education. As the Vice President of Innovation at OCHIN, he has spearheaded numerous initiatives that leverage advanced technologies to enhance operational efficiency and improve patient care. With extensive experience implementing AI frameworks, developing technology roadmaps, and fostering cross-functional collaboration, Dr. Fernandez is renowned for his strategic insight and innovative solutions that address real-world challenges. In addition to his role at OCHIN, he serves as a senior advisor for innovation and technology for the Secretary of Health in the Dominican Republic and as a Technology Advisor for the St. Marteen Embassy for the Dominican Republic.",
    photo: "/images/speakers/dhc-2024/engers-fernandez.jpg",
  },
  "rouella-mendonca": {
    id: "rouella-mendonca",
    name: "Rouella Mendonca",
    title: "Artificial Intelligence Product Lead",
    organization: "Audere",
    bio: "Rouella Mendonca has over 15 years experience building scalable, innovative digital solutions across biotech, global health, and industry leaders like Microsoft. She is the Artificial Intelligence Product Lead at Audere, a digital health non-profit, leading strategy, roadmap, implementation, and partnerships for HealthPulse AI to improve equity in access and outcomes for healthcare in low and middle income countries. She has extensive experience delivering accessible health tech solutions and digital platforms that incorporate artificial intelligence including computer vision, machine learning, and natural language processing.",
    photo: "/images/speakers/dhc-2024/rouella-mendonca.jpg",
  },
  "bronte-sihan-li": {
    id: "bronte-sihan-li",
    name: "Bronte Sihan Li",
    credentials: "MS, MLS(ASCP)",
    title: "AI Software Engineer",
    organization: "Audere",
    bio: "Bronte is an AI Software Engineer specializing in health solutions and interdisciplinary applications of AI. She holds an MS in Computer Science from Northeastern University and a BS in Medical Laboratory Science from the University of Washington. Currently at Audere, her work focuses on multi-LLM integration and AI-driven care. Bronte's research includes contributions to healthcare and environmental AI applications, with notable publications in prominent IEEE conferences.",
    photo: "/images/speakers/dhc-2024/bronte-sihan-li.jpg",
  },
  "laura-jantos": {
    id: "laura-jantos",
    name: "Laura Jantos",
    title: "Principal Advisor",
    organization: "RecastHealth",
    bio: "Laura Jantos is Principal Advisor with RecastHealth and a nationally recognized thought leader and expert in digital health and technology having held leadership positions in a national consulting firm. A Traumatic Brain Injury (TBI) necessitated her retirement from healthcare IT but her recovery reignited her passion for technology that empowers all people to understand and manage their health. She has led regional and national initiatives to implement shared technology solutions to put the patient at the center of care. Laura serves as a Technical Expert on Artificial Intelligence for the National Quality Forum. She is a life Fellow of HIMSS and held positions at the national and state level including Chair of several HIMSS national committees and President and Board Member of HIMSS WA.",
    photo: "/images/speakers/dhc-2024/laura-jantos.jpg",
  },
  "apurva-zawar": {
    id: "apurva-zawar",
    name: "Apurva Zawar",
    credentials: "PT, DPT, GCS",
    title: "Founder, BeyondRehab",
    organization: "BeyondRehab / UCSF",
    bio: "Apurva Zawar is the founder of BeyondRehab, a pioneering digital Neuro-Rehab & Wellness clinic, and Volunteer Assistant Clinical Professor at UCSF. Specializing in the integration of digital health solutions into neurologic and geriatric care, she is committed to improving patient outcomes across both rural and urban populations. She also serves as a board member of the American Parkinson Disease Association (APDA) - Northwest Chapter. She is at the forefront of developing innovative care models that leverage technology to enhance healthcare access and chronic disease management, with a focus on patient-centered care and population health.",
    photo: "/images/speakers/dhc-2024/apurva-zawar.jpg",
  },
  "helen-schnase": {
    id: "helen-schnase",
    name: "Helen Schnase",
    credentials: "MD, MBA, FAAFP",
    title: "Vice President, Clinic Services",
    organization: "Transcarent",
    bio: "Helen is a dynamic healthcare leader and practicing physician with 15+ years of experience in the field. As the Vice President of Clinic Services at Transcarent, she leads a team dedicated to providing high-quality, accessible care 24/7, 365 through an innovative, on-demand clinic model. Helen oversees several teams, including Clinical Quality and Safety, Learning and Development, Member Support, Clinic Operations, and Medical Group Operations. She is deeply committed to improving health outcomes, expanding access to care, and enhancing the clinician and member experience, and is actively involved in developing new service lines and strategies focused on clinical integration and care pathways.",
    photo: "/images/speakers/dhc-2024/helen-schnase.jpg",
  },
  "dana-lewis": {
    id: "dana-lewis",
    name: "Dana Lewis",
    title: "Founder, OpenAPS",
    organization: "",
    bio: "Dana Lewis is an independent researcher, developer, and author with decades of experience at the intersection of different types of technology, health, and healthcare. Dana founded the open source artificial pancreas movement (known as \"OpenAPS\"), making safe and effective automated insulin delivery (AID) technology available (sooner) for people with diabetes around the world. The algorithm Dana developed is still in use by thousands of people with diabetes almost a decade later. Her efforts now include making AI-powered technology such as LLM capabilities available within tools for direct use by patients.",
    photo: "/images/speakers/dhc-2024/dana-lewis.jpg",
    photoPosition: "30% center",
  },
  "deana-bell": {
    id: "deana-bell",
    name: "Deana Bell",
    credentials: "FSA, MAAA",
    title: "Principal and Consulting Actuary",
    organization: "Milliman",
    bio: "Deana Bell is a Principal and Consulting Actuary at Milliman's Seattle office. She joined Milliman in 2005 and has extensive experience in the health insurance sector, focusing on pricing products, financial reporting, benchmarking, healthcare analytics, predictive analytics, and value-based care. Deana works with group healthcare programs, including Medicare and Medicaid plans, Veterans Health Administration, provider groups, and health tech startups.",
    photo: "/images/speakers/dhc-2024/deana-bell.jpg",
    photoPosition: "center 30%",
  },
  "austin-barrington": {
    id: "austin-barrington",
    name: "Austin Barrington",
    credentials: "FSA, MAAA",
    title: "Principal and Consulting Actuary",
    organization: "Milliman",
    bio: "Austin Barrington is a Principal and Consulting Actuary at Milliman's Seattle office. Since joining Milliman in 2020, he has specialized in healthcare consulting, offering expertise in areas such as provider reimbursement benchmarking, claims and membership analytics, and the development of custom risk scoring models. His experience spans work with care management organizations, digital health companies, health plans, and providers. Prior to Milliman, Austin spent eight years at Health Care Service Corporation, where he led evaluations of care management programs and developed predictive analytics initiatives.",
    photo: "/images/speakers/dhc-2024/austin-barrington.jpg",
    photoPosition: "center 30%",
  },
  "neha-patadia": {
    id: "neha-patadia",
    name: "Neha Patadia",
    credentials: "MS",
    title: "Founder",
    organization: "Datum",
    bio: "Neha Patadia is a dynamic professional driven to improve healthcare experiences. With McKinsey backbone and experiences across public and private sectors in healthcare, she has developed a comprehensive understanding of the business of healthcare and healthcare innovation. She has collaborated with providers, CMS and startups to lead product development teams from 0-1, always at the forefront of AI applications in consumer-centric strategies. Now, as the founder of Datum, she's developing predictive models and tools to utilize precision medicine to make personalized healthcare more accessible to all and ultimately improve health outcomes.",
    photo: "/images/speakers/dhc-2024/neha-patadia.jpg",
  },
  "jenn-yoo": {
    id: "jenn-yoo",
    name: "Jenn Yoo",
    title: "Partner",
    organization: "Fenwick & West",
    bio: "Jenn Yoo, a Partner at Fenwick & West, specializes in advising healthcare industry companies on regulatory and transactional matters. She works with healthtech, digital health companies, healthcare providers, medical device, therapeutics, diagnostics, and life sciences organizations. Jenn offers expertise in digital health laws, virtual care, teleprescribing, healthcare licensing, reimbursement compliance, and HIPAA data privacy. She also helps clients navigate value-based care models and care coordination. Jenn is an active member of the American Health Lawyers Association and the American Bar Association Health Law Section.",
    photo: "/images/speakers/dhc-2024/jenn-yoo.jpg",
  },
  "rashmi-rao": {
    id: "rashmi-rao",
    name: "Rashmi Rao",
    title: "Founder",
    organization: "rcubed | ventures / HLWF Alliance",
    bio: "Rashmi Rao is an entrepreneur and inventor with 40+ patents and demonstrated prowess in transforming ideas to lucrative tech and healthcare businesses generating $500M+ revenue at QCOM, APPL, Samsung, Philips. She founded rcubed | ventures and non-profit HLWF Alliance focused on women's health and strives to work at the intersection of technology, public health and public policy. Inducted into Women in Tech Hall of Fame, she champions diversity and health equity, influencing STEM through Board roles at University of Washington (Engineering Innovation in Health), World Affairs Council-Seattle, and World Economic Forum.",
    photo: "/images/speakers/dhc-2024/rashmi-rao.jpg",
  },
  "estelle-giraud": {
    id: "estelle-giraud",
    name: "Estelle Giraud",
    credentials: "PhD",
    title: "Cofounder and CEO",
    organization: "Trellis Health",
    bio: "Dr. Estelle Giraud is the cofounder and CEO of Trellis Health, a comprehensive health-tech company focused on helping families build generational health and shaping a future of precision medicine. She's a scientist and self-proclaimed data nerd, with an undergrad in Psychology and Genetics and a PhD in Population Genomics from the University of Western Australia. Prior to Trellis, she spent 8 years as a commercial operator, pioneering genomic technologies at Illumina where she led the US commercial team for consumer genomics and precision medicine and grew the business to $400M annual revenue.",
    photo: "/images/speakers/dhc-2024/estelle-giraud.jpg",
  },
  "karishma-patel": {
    id: "karishma-patel",
    name: "Karishma Patel",
    title: "Co-Founder and CXO",
    organization: "Ema",
    bio: "Karishma Patel is a tech entrepreneur with a background in product development and marketing, specializing in generative AI. As the co-founder and CXO of Ema, the first AI-driven platform designed to support women's health from menstruation to menopause, she is passionate about leveraging technology to empower women with personalized, evidence-based health information. Karishma's work embodies the transformative potential of AI in reshaping healthcare, particularly in improving women's health outcomes and access to care.",
    photo: "/images/speakers/dhc-2024/karishma-patel.jpg",
  },
};

export const schedule: DaySchedule[] = [
  {
    day: "Day 1",
    date: "Tuesday, October 8, 2024",
    sessions: [
      { time: "8:00 – 8:30 a.m.", title: "Registration, Breakfast & Networking", type: "break" },
      {
        time: "8:30 – 9:15 a.m.",
        title: "Strategic Counsel: Advancing AI and Data-Driven Innovation in Healthcare",
        speakerIds: ["dave-schoolcraft"],
      },
      {
        time: "9:15 – 9:45 a.m.",
        title: "The Role of Machine Learning in Precision Medicine",
        speakerIds: ["martin-stumpe"],
      },
      {
        time: "9:45 – 10:15 a.m.",
        title: "AI in the ER: Bridging Technical Advancements, Regulatory Issues, and Clinical Impact in the Modern ER",
        speakerIds: ["tayab-waseem"],
      },
      { time: "10:15 – 10:45 a.m.", title: "Break & Networking", type: "break" },
      {
        time: "10:45 – 11:15 a.m.",
        title: "Federal Policy Empowering Innovation — A Conversation with Sebastian Jayaraj",
        speakerIds: ["sebastian-jayaraj", "jefferson-lin"],
      },
      {
        time: "11:15 a.m. – 12:00 p.m.",
        title: "Legal and Technical Collaboration in Developing FDA Regulated Technology",
        speakerIds: ["maggie-huston", "brandon-fornwalt"],
      },
      { time: "12:00 – 1:30 p.m.", title: "Lunch", type: "break" },
      {
        time: "1:30 – 2:00 p.m.",
        title: "Recent Developments at the ASTP (formerly ONC) — Data Interoperability, Information Blocking, TEFCA, and AI Regulation",
        speakerIds: ["michael-lipinski", "mark-knee"],
      },
      {
        time: "2:00 – 2:30 p.m.",
        title: "Data Liquidity in Practice: Observations from the Front Lines of the Data Wars",
        speakerIds: ["matthew-holt", "brendan-keeler"],
      },
      { time: "2:30 – 3:00 p.m.", title: "Break & Networking", type: "break" },
      {
        time: "3:00 – 3:45 p.m.",
        title: "Working with Digital Health Start-Ups, Investors, and Innovators",
        speakerIds: ["kat-duncan", "oren-nissim", "casey-moriarty", "jenny-cronin"],
      },
      {
        time: "3:45 – 4:15 p.m.",
        title: "Charting the Course: Navigating the Evolving Regulatory Environment",
        speakerIds: ["adriana-lein", "doreen-fadaeiforghan", "katherine-robertson"],
      },
      {
        time: "4:15 – 5:00 p.m.",
        title: "Health Product Counseling: Bridging Technology and Law",
        speakerIds: ["ty-kayam", "alieza-ali"],
      },
      { time: "5:00 – 6:00 p.m.", title: "Reception — 40th Floor Board Room", type: "break" },
    ],
  },
  {
    day: "Day 2",
    date: "Wednesday, October 9, 2024",
    sessions: [
      { time: "8:00 – 9:00 a.m.", title: "Registration, Breakfast & Networking", type: "break" },
      {
        time: "9:00 – 10:00 a.m.",
        title: "LLM 101 + Capabilities of GPT-4 on Medical Challenge Problems",
        speakerIds: ["harsha-nori"],
      },
      { time: "10:00 – 10:25 a.m.", title: "Break", type: "break" },
      {
        time: "10:25 – 11:10 a.m.",
        title: "From Algorithms to Accountability: AI and Medical Malpractice Liability",
        speakerIds: ["glenn-cohen"],
      },
      {
        time: "11:15 a.m. – 12:00 p.m.",
        title: "AI Governance in Focus: Addressing Ethical and Regulatory Challenges",
        speakerIds: ["elana-zana", "matt-soskins", "zach-harned", "engers-fernandez"],
      },
      { time: "12:00 – 1:30 p.m.", title: "Lunch", type: "break" },
      {
        time: "1:30 – 2:00 p.m.",
        title: "Global Health Initiative: Impact of AI in the Fight against HIV and Malaria",
        speakerIds: ["rouella-mendonca", "bronte-sihan-li"],
      },
      {
        time: "2:00 – 2:30 p.m.",
        title: "The Patient Will See You Now: Leveraging AI to Put Patients in the Center",
        speakerIds: ["laura-jantos", "apurva-zawar", "helen-schnase", "dana-lewis"],
      },
      { time: "2:30 – 3:00 p.m.", title: "Break & Networking", type: "break" },
      {
        time: "3:00 – 3:45 p.m.",
        title: "AI and Health Transparency Data Bending Employer-Sponsored Healthcare Costs",
        speakerIds: ["deana-bell", "austin-barrington", "neha-patadia"],
      },
      {
        time: "3:45 – 4:30 p.m.",
        title: "Femtech Futures: Policy and Tech Innovations in Women's Health",
        speakerIds: ["jenn-yoo", "rashmi-rao", "estelle-giraud", "karishma-patel"],
      },
      { time: "4:30 – 4:45 p.m.", title: "Closing Remarks", type: "break" },
    ],
  },
];
